language: python
python:
 - '3.8'
before_install:
 - sudo apt-get update
install:
 - pip install -r requirements.txt --allow-all-external
script:
 - pytest --cov-config=.coveragerc --cov=sem_size_analysis tests/
 - flake8