FROM python:3.6-slim-stretch

RUN apt-get update && apt-get install -y git python3-dev gcc \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .

RUN pip install --upgrade -r requirements.txt

COPY . app/
WORKDIR app/

EXPOSE 8000

CMD ["gunicorn", "--bind", "0.0.0.0:8000", "src.backend_api:flask_app"]